# docker build -t container_upgraded -f container_upgraded/Dockerfile  .; docker run --rm --name  container_upgraded container_upgraded;
FROM simple_tool:container_upgraded

WORKDIR code_correction/repositories/simple_tool

COPY . .


